
from enum import Enum
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class CustomerTier(str, Enum):
    """Customer tier levels"""
    ENTERPRISE = "enterprise"
    BUSINESS = "business"
    STANDARD = "standard"
    FREE = "free"


class UrgencyLevel(str, Enum):
    """AI-determined urgency levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SentimentType(str, Enum):
    """Customer sentiment"""
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"


class FeedbackType(str, Enum):
    """Agent feedback on priority accuracy"""
    TOO_HIGH = "too_high"
    CORRECT = "correct"
    TOO_LOW = "too_low"


class LLMSignals(BaseModel):
    """Signals generated by LLM"""
    summary: Optional[str] = None
    urgency: Optional[UrgencyLevel] = None
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    sentiment: Optional[SentimentType] = None
    sentiment_intensity: Optional[float] = Field(None, ge=0.0, le=1.0)
    generated_at: Optional[datetime] = None
    error: Optional[str] = None  # If LLM fails


class PriorityBreakdown(BaseModel):
    """Detailed breakdown of priority score calculation"""
    effective_urgency: float = Field(ge=0.0, le=1.0)
    sla_risk: float = Field(ge=0.0, le=1.0)
    customer_tier_weight: float = Field(ge=0.0, le=1.0)
    final_score: float = Field(ge=0.0, le=1.0)
    
    # Component contributions
    urgency_contribution: float = Field(ge=0.0, le=1.0)
    sla_contribution: float = Field(ge=0.0, le=1.0)
    tier_contribution: float = Field(ge=0.0, le=1.0)
    
    calculated_at: datetime = Field(default_factory=datetime.utcnow)


class Ticket(BaseModel):
    """Main ticket model"""
    # Core fields
    ticket_id: str
    text: str
    customer_tier: CustomerTier
    customer_name: Optional[str] = None  # ← Add this
    customer_email: Optional[str] = None  # ← Add this
    customer_account_id: Optional[str] = None  # ← Add this
    sla_hours_remaining: float
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # LLM-generated signals
    llm_signals: Optional[LLMSignals] = None
    
    # Priority scoring
    priority_score: float = Field(default=0.0, ge=0.0, le=1.0)
    priority_band: str = Field(default="P3")  # ← Add this line
    priority_breakdown: Optional[PriorityBreakdown] = None
    
    # Human override
    manual_override: bool = False
    override_priority: Optional[float] = Field(None, ge=0.0, le=1.0)
    override_reason: Optional[str] = None
    override_at: Optional[datetime] = None
    override_by: Optional[str] = None
    
    # Agent feedback (post-resolution)
    feedback: Optional[FeedbackType] = None
    feedback_at: Optional[datetime] = None
    feedback_by: Optional[str] = None
    
    # Status
    status: str = "open"  # open, in_progress, resolved
    assigned_to: Optional[str] = None
    resolved_at: Optional[datetime] = None
    
    @property
    def effective_priority(self) -> float:
        """Get the effective priority (override if exists, else computed)"""
        if self.manual_override and self.override_priority is not None:
            return self.override_priority
        return self.priority_score
    



class TicketCreate(BaseModel):
    """Request model for creating a new ticket"""
    text: str = Field(min_length=10, max_length=5000)
    customer_tier: CustomerTier
    sla_hours_remaining: float = Field(gt=0)
    customer_name: Optional[str] = None 
    customer_email: Optional[str] = None
    customer_account_id: Optional[str] = None

class TicketUpdate(BaseModel):
    """Request model for updating ticket"""
    text: Optional[str] = None
    sla_hours_remaining: Optional[float] = None
    status: Optional[str] = None
    assigned_to: Optional[str] = None


class ManualOverride(BaseModel):
    """Request model for manual priority override"""
    override_priority: float = Field(ge=0.0, le=1.0)
    override_reason: str = Field(min_length=5)
    override_by: str


class TicketFeedback(BaseModel):
    """Request model for agent feedback"""
    feedback: FeedbackType
    feedback_by: str